### ISSUE TITLE
need bricks

### ISSUE THREAD

**Issue by ebobtron** [ebobtron/WinBreakoutCPlusPlus#5]
Our bricks will have properties  and those should be:
- RECT structure containing long left, top, right, bottom
- COLORREF pen;  the color of the outline drawn.
- COLORREF brush,  the brush color for the rectangle.

any other qualities, traits, properties ???

Then it can look like this for now.

```
/**   global structure for brick   **/
struct tHEBRICK{
  RECT rcBrick;
  COLORREF pen;
  COLORREF brush;
};
```

current brick code
**https://gist.github.com/ebobtron/b59fa6b0518346d4591c**
edit: add gist link for current brick code

**Comment by TsukishirOSan** [comment]
Gotta create them!

2015-04-23 0:03 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
Like pondering the world.  What is a brick?

**Comment by TsukishirOSan** [comment]
Well oop experience tells me it's an object, but here it's coordinates in a
window. both cases btw. so : width and length, and placing them wrt the
window's size

2015-04-23 8:23 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
in this particular case a brick is a rectangle defined by a structure RECT  https://msdn.microsoft.com/en-us/library/windows/desktop/dd162897%28v=vs.85%29.aspx .

We will need many `RECT brick;` definitions to get the number of needed object variables like `brick`.  
Should our bricks have color we have color of the pen, that outlines a brick and the brush, that fills the brick

Do we create a structure of our own that has RECT rect and a COLORREF pen and COLORREF brush.

95 % of this is simple C the exception being the windows Class.  I thought if some are inclined we could branch off into a more OOP experence with GDI+ ( https://msdn.microsoft.com/en-us/library/windows/desktop/ms533798%28v=vs.85%29.aspx )  at some future time so far the number are small.

**Comment by TsukishirOSan** [comment]
Ok, I gotta look at it, see the syntax differences and do you want me to
create a rect class for both bricks and paddle, then instanciate bricks and
paddle?

2015-04-23 10:05 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
No I'll do this, but do we think we have enough brick elements?  So, how big, how many and should bricks be on the heap or the stack.

how much memory needed for 50 bricks.  Unlike the the SPL objects, we will need to track the bricks. There won't be an unrecorded object out there somewhere to inform us about which brick gets hit.

We could write a Brick Class but that is a little overkill at this point in the program and would require us to track a unique number against a rectangle anyway.  No advantages.

So do we do:

`tHEBRICK brick[50];`    // this works 
`tHEBRICK* brick[50];`  // not sure about this

**Comment by TsukishirOSan** [comment]
I saw how you did paddle and I wanted to do the same, well use the same
obects for paddle but it took me forever to find the windows' size: I m a
noob at that, and...I just want to get used to VS and C++ to send you the
bricks part
init bricks and probably destroy

2015-04-25 5:37 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
All is good, I wanted to demonstrate a structure in a structure thing that Windows does so much of.
If you have this working on VS or are working on it, that is super great.  I did not do all the work, I am just demonstrating to myself that this will work.  I added a function to make a single brick, which is called by a make wall function. added a draw wall / bricks function to shoe horn in and test the results.  So far my notions about direction for this are valid, "if best way to do it", is arguable.

one brick on the screen,  I will push this tomorrow and work on the webpage, allow you to get more caught up.

Thanks for the interest.

**Comment by TsukishirOSan** [comment]
I want to test stuff like, for instance, I wanted to output the values of
sizeY and size X since I m gonna need them for the bricks size, but..... I
get an exit code of 0x00 when I run i, and that's it, no output whatsoever.
So if you could help me out with that, a bit, I'll ask my husband when he's
up, since i find noth VS and Eclipse really similar :)

2015-04-25 9:21 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
if you are trying to output something in a windows program you need to use a different technique because the is no standard out place to put the data. See the following code.

```
char buf[32];
sprintf(buf,"%d",sizeof(infobrick));
MessageBox(NULL,    // NULL so the box is not trapped inside a window
                         buf,    // the character buffer above
  "sizeof(infobrick)",    // title for the little box
                  MB_OK);  // windows constant the make the ok button an OK button
```

click me **[MessageBox()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645505%28v=vs.85%29.aspx)**
I am working on a console solution so we can see values change withot fighting with the debugger.
I hope I understood you.  If not OK   send me some code ?? this gist thing here is under utilized.

**Comment by ebobtron** [comment]
This is resolved if forgotten, though a more clever way of mapping bricks is possible and wanted.
