### ISSUE TITLE
enableing the use of printf for dumping variable values.

### ISSUE THREAD

**Issue by ebobtron** [ebobtron/WinBreakoutCPlusPlus#6]
Place this code inside WinMain before the "Message Loop"  then whenever you wish to see a value use printf() like any other program.   Note your likely to see running lists. 

try putting `printf("x = %d  y = %d\n", ballRect.left, ballRect.right);`  following "move the ball" in the updateGame() function in breakout.cpp

If you wish to use `cout` as in `std::cout << "x= " << ballRect.left << "  y = " << ballRect.right << "\n";`
you will need to link the static library  `libcmtd.lib`

```
if(!AllocConsole()){
    MessageBox(NULL, _T(" can not create console window "),
                     _T(" WinBreakoutC++ "), MB_OK);
}
freopen("CONOUT$","wb",stdout);  // reopen stout handle as console window output
```

if you wrap `#ifdef _DEBUG` and `#endif`  around this code the compiler can included it when debug is set as a build option.

**Comment by ebobtron** [comment]
the use of `freopen("CONOUT$","wb",stdout);` throws a compiler warning about security issues the details of which are unknown and unimportant.  The recommended `freopen_s` is now in place as in the example below.   Note the use of a file pointer np.  freopen_s is not going to work in this instance without it.

```
FILE* np;    // file pointer for freopen_s secure
freopen_s(&np, "CONOUT$", "wb", stdout);  // reopen stout handle as console window output
```

**Comment by FreeER** [comment]
> Note the use of a null pointer, at least I think that is what that is.

This is not a null pointer in any way. It is an uninitialized file pointer whose address is being passed to freopen_s so that it can store the file\* of the newly opened file ("CONOUT$") since freopen_s returns a errno_t type (instead of just null on errors like freopen). Not entirely sure why this works though...

```
// reopen stout handle as console window output
FILE* oldstdout = stdout;
FILE* np = 0; // file pointer for freopen_s to store address of newly opened file (aka CONOUT$)?
freopen_s(&np, "CONOUT$", "wb", stdout);
printf("np is %p and stdout is %p\nstdout was: %p", np, stdout, oldstdout);
```

proves that's what it's doing... and yet

Therefore I'd have thought the proper code would be something like this: but that fails utterly since stdout isn't a global constant but a macro for `(&__iob_func()[1])`....

```
freopen_s(&stdout, "CONOUT$", "wb", stdout);
```

OR simply unneeded if perhaps AllocConsole was setting stdout, but without the freopen(_s) it doesn't work either lol.

hm, perhaps stdout isn't opened as writable without a console and _that's_ what the freopen call is doing? not sure how to check to find out (not that it matters _too_ much, but education!)

**Comment by ebobtron** [comment]
I can Google too and if I hadn't it would not be working.  My lack of formal training shows and yet.  If AllocConsole worked without freopen you wouldn't have seen the compiler warning.

neener-neener-neener

**Comment by ebobtron** [comment]
stdout and stdin are streams in windows whatever the actually means. A "windows console" has an "in" and "out" that appear to be the special files names ("CONOUT$")  ("CONIN$") and maybe others.  freopen_s reassigns the pointer so that where ever stdout was pointing to it now points to the console. That's my take on the reading material.

What the actual difference is between functions is hard to determine.

```
FILE* cp = freopen("CONOUT$", "w", stdout);
```

or

```
FILE* cp;
freopen_s(&cp,  "CONOUT$", "wb", stdout);
```

You'd think to provide the security enhancements suggested in https://msdn.microsoft.com/en-us/library/8ef0s5kh.aspx  that there might be more to it.

EDIT: there was a mistake in the second example `freopen` instead of `freopen_s`

**Comment by TsukishirOSan** [comment]
I'd go for the second one checking for freopen to have worked just fine to
avoid unexpected behaviors

2015-04-28 4:11 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
the recommendation is to use the second one and we shall.

**Comment by ebobtron** [comment]
this is not really an issues as the workings of this are implemented and handy.
